code/marvin/src/main/java/br/ufes/informatica/marvin/research/domain/BibGenConfiguration.java
package br.ufes.informatica.marvin.research.domain;

import java.util.Set;
import java.util.TreeSet;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.validation.constraints.Min;
import javax.validation.constraints.Size;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;
import br.ufes.informatica.marvin.core.domain.Academic;

/**
 * TODO: document this type.
 *
 * @author Vítor E. Silva Souza (https://github.com/vitorsouza/)
 */
@Entity
public class BibGenConfiguration extends PersistentObjectSupport {
  /** The unique identifier for a serializable class. */
  private static final long serialVersionUID = 1L;

  /** TODO: document this field. */
  @Size(max = 30)
  private String name;

  /** TODO: document this field. */
  @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
  private Set<BibGenResearcher> researchers = new TreeSet<>();

  /** TODO: document this field. */
  @Min(0)
  private Integer startYear;

  /** TODO: document this field. */
  @Min(0)
  private Integer endYear;

  /** Getter for name. */
  public String getName() {
    return name;
  }

  /** Setter for name. */
  public void setName(String name) {
    this.name = name;
  }

  /** Getter for researchers. */
  public Set<BibGenResearcher> getResearchers() {
    return researchers;
  }

  /** Setter for researchers. */
  protected void setResearchers(Set<BibGenResearcher> researchers) {
    this.researchers = researchers;
  }

  /** Getter for startYear. */
  public Integer getStartYear() {
    return startYear;
  }

  /** Setter for startYear. */
  public void setStartYear(Integer startYear) {
    this.startYear = startYear;
  }

  /** Getter for endYear. */
  public Integer getEndYear() {
    return endYear;
  }

  /** Setter for endYear. */
  public void setEndYear(Integer endYear) {
    this.endYear = endYear;
  }

  /**
   * TODO: document this method.
   * 
   * @param researcher
   * @param startYear
   * @param endYear
   */
  public void addResearcher(Academic researcher, Integer startYear, Integer endYear) {
    researchers.add(new BibGenResearcher(researcher, startYear, endYear));
  }
}

code/marvin/src/main/java/br/ufes/informatica/marvin/research/domain/BibGenResearcher.java
package br.ufes.informatica.marvin.research.domain;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;
import br.ufes.informatica.marvin.core.domain.Academic;

/**
 * TODO: document this type.
 *
 * @author Vítor E. Silva Souza (https://github.com/vitorsouza/)
 */
@Entity
public class BibGenResearcher extends PersistentObjectSupport
    implements Comparable<BibGenResearcher> {
  /** The unique identifier for a serializable class. */
  private static final long serialVersionUID = 1L;

  /** TODO: document this field. */
  @ManyToOne
  private Academic researcher;

  /** TODO: document this field. */
  private Integer startYear;

  /** TODO: document this field. */
  private Integer endYear;

  /** Constructor. */
  protected BibGenResearcher() {}

  /** Constructor. */
  public BibGenResearcher(Academic researcher, Integer startYear, Integer endYear) {
    this.researcher = researcher;
    this.startYear = startYear;
    this.endYear = endYear;
  }

  /** Getter for researcher. */
  public Academic getResearcher() {
    return researcher;
  }

  /** Setter for researcher. */
  public void setResearcher(Academic researcher) {
    this.researcher = researcher;
  }

  /** Getter for startYear. */
  public Integer getStartYear() {
    return startYear;
  }

  /** Setter for startYear. */
  public void setStartYear(Integer startYear) {
    this.startYear = startYear;
  }

  /** Getter for endYear. */
  public Integer getEndYear() {
    return endYear;
  }

  /** Setter for endYear. */
  public void setEndYear(Integer endYear) {
    this.endYear = endYear;
  }

  @Override
  public int compareTo(BibGenResearcher o) {
    return researcher.compareTo(o.researcher);
  }

  @Override
  public boolean equals(Object obj) {
    if (!(obj instanceof BibGenResearcher))
      return false;
    return researcher.equals(((BibGenResearcher) obj).researcher);
  }

  @Override
  public int hashCode() {
    return researcher.hashCode();
  }
}

code/marvin/src/main/java/br/ufes/informatica/marvin/research/domain/Book.java
package br.ufes.informatica.marvin.research.domain;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;

/**
 * TODO: document this type.
 *
 * @author Thiago Rocha Salvatore (https://github.com/thiagosalvatore)
 * @author Vítor E. Silva Souza (https://github.com/vitorsouza/)
 */
@Entity
@DiscriminatorValue("book")
public class Book extends Publication {
  /** The unique identifier for a serializable class. */
  private static final long serialVersionUID = 1L;

  /** TODO: document this field. */
  private String edition;

  /** Constructor. */
  protected Book() {}

  /** Constructor. */
  public Book(String title, int year, String pages, String doi, String publisher, String edition) {
    super(title, year, pages, doi, publisher);
    this.edition = edition;
  }

  /** Getter for edition. */
  public String getEdition() {
    return edition;
  }

  /** Setter for edition. */
  public void setEdition(String edition) {
    this.edition = edition;
  }

  @Override
  public String getVenueString() {
    return "";
  }

  @Override
  public String toBibTeX() {
    StringBuilder builder = new StringBuilder();

    // Produces the BibTeX entry for this type of publication.
    builder.append("@book{").append(getBibKey()).append(",\n"); // @book{bibKey,
    builder.append("\ttitle = {{").append(title).append("}},\n"); // title = {{Publication's
                                                                  // Title}},
    builder.append("\tauthor = {").append(getAuthorList().toUpperCase()).append("},\n"); // author =
                                                                                         // {Author
                                                                                         // list},
    if (edition != null && !edition.isEmpty())
      builder.append("\tedition = {").append(edition).append("},\n"); // edition
                                                                      // =
                                                                      // {Book
                                                                      // edition},
    if (doi != null && !doi.isEmpty())
      builder.append("\tdoi = {").append(doi).append("},\n"); // doi = {Digital Object
                                                              // Identifier},
    if (publisher != null && !publisher.isEmpty())
      builder.append("\tpublisher = {{").append(publisher).append("}},\n"); // publisher
                                                                            // =
                                                                            // {{Publisher's
                                                                            // name}},
    builder.append("\tyear = {").append(getYear()).append("}\n"); // year = {Publication year}
    builder.append("}\n"); // }

    return builder.toString();
  }
}

code/marvin/src/main/java/br/ufes/informatica/marvin/research/domain/VenueCategory.java
package br.ufes.informatica.marvin.research.domain;

/**
 * TODO: document this type.
 *
 * @author Vítor E. Silva Souza (https://github.com/vitorsouza/)
 */
public enum VenueCategory {
  CONFERENCE("Conference"), 
  JOURNAL("Journal");

  /** TODO: document this field. */
  String name;

  /** Getter for category name. */
  public String getName() {
    return name;
  }

  /** Setter for category name. */
  public void setName(String name) {
    this.name = name;
  }

  /** Constructor. */
  VenueCategory(String name) {
    this.name = name;
  }
}

code/marvin/src/main/java/br/ufes/informatica/marvin/research/application/GenerateBibliographyServiceBean.java
package br.ufes.informatica.marvin.research.application;

import java.util.List;
import java.util.SortedSet;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.security.RolesAllowed;
import javax.ejb.EJB;
import javax.ejb.Stateless;
import br.ufes.informatica.marvin.core.domain.Academic;
import br.ufes.informatica.marvin.research.domain.BibGenConfiguration;
import br.ufes.informatica.marvin.research.domain.BibGenResearcher;
import br.ufes.informatica.marvin.research.domain.Publication;
import br.ufes.informatica.marvin.research.persistence.PublicationDAO;

/**
 * TODO: document this type.
 *
 * @author Vítor E. Silva Souza (https://github.com/vitorsouza/)
 */
@Stateless
@RolesAllowed({"SysAdmin", "Professor"})
public class GenerateBibliographyServiceBean implements GenerateBibliographyService {
  /** The unique identifier for a serializable class. */
  private static final long serialVersionUID = 1L;

  /** Logger for this class. */
  private static final Logger logger =
      Logger.getLogger(GenerateBibliographyServiceBean.class.getCanonicalName());

  /** TODO: document this field. */
  @EJB
  private PublicationDAO publicationDAO;

  @Override
  public StringBuilder generateBibliography(BibGenConfiguration config) {
    StringBuilder builder = new StringBuilder();

    // Goes through all the researchers, adding their publications to a single sorted set.
    SortedSet<Publication> publications = new TreeSet<>();
    for (BibGenResearcher researcherCfg : config.getResearchers()) {
      Academic researcher = researcherCfg.getResearcher();
      logger.log(Level.INFO, "Adding publications of \"{0}\" ({1}), start: {2}, end: {3}",
          new Object[] {researcher.getName(), researcher.getEmail(), researcherCfg.getStartYear(),
              researcherCfg.getEndYear()});

      // Retrieves the publications within the year range and add them to the set.
      List<Publication> researcherPublications = publicationDAO.retrieveByAcademicAndYearRange(
          researcher, researcherCfg.getStartYear(), researcherCfg.getEndYear());
      publications.addAll(researcherPublications);
    }

    // Prints all publications in the sorted set to the string output.
    for (Publication publication : publications)
      builder.append(publication.toBibTeX()).append("\n\n");

    // Returns the string builder with the entire bibliography.
    return builder;
  }
}

code/marvin/src/main/java/br/ufes/informatica/marvin/research/application/ListResearchersServiceBean.java
package br.ufes.informatica.marvin.research.application;

import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.security.RolesAllowed;
import javax.ejb.EJB;
import javax.ejb.Stateless;
import br.ufes.informatica.marvin.core.domain.Academic;
import br.ufes.informatica.marvin.core.persistence.AcademicDAO;
import br.ufes.informatica.marvin.research.persistence.PublicationDAO;

/**
 * TODO: document this type.
 *
 * @author Vítor E. Silva Souza (https://github.com/vitorsouza/)
 */
@Stateless
@RolesAllowed({"SysAdmin", "Professor"})
public class ListResearchersServiceBean implements ListResearchersService {
  /** The unique identifier for a serializable class. */
  private static final long serialVersionUID = 1L;

  /** Logger for this class. */
  private static final Logger logger =
      Logger.getLogger(ListResearchersServiceBean.class.getCanonicalName());

  /** TODO: document this field. */
  @EJB
  private AcademicDAO academicDAO;

  /** TODO: document this field. */
  @EJB
  private PublicationDAO publicationDAO;

  @Override
  public List<Academic> listResearchers() {
    logger.log(Level.INFO, "Listing researchers...");

    // Retrieves the researchers, sorts the list and returns.
    List<Academic> researchers = academicDAO.retrieveResearchers();
    Collections.sort(researchers);
    return researchers;
  }

  @Override
  public Long countPublications(Academic researcher) {
    logger.log(Level.INFO, "Retrieving the number of publications of a researcher...");
    return publicationDAO.retrieveCountByAcademic(researcher);
  }
}

code/marvin/src/main/java/br/ufes/informatica/marvin/research/application/UploadLattesCVServiceBean.java
package br.ufes.informatica.marvin.research.application;

import java.io.InputStream;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.security.RolesAllowed;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.ejb.Stateless;
import javax.enterprise.event.Event;
import javax.inject.Inject;
import br.ufes.inf.nemo.jbutler.ejb.controller.PersistentObjectConverterFromId;
import br.ufes.inf.nemo.jbutler.ejb.persistence.exceptions.MultiplePersistentObjectsFoundException;
import br.ufes.inf.nemo.jbutler.ejb.persistence.exceptions.PersistentObjectNotFoundException;
import br.ufes.informatica.marvin.core.domain.Academic;
import br.ufes.informatica.marvin.core.persistence.AcademicDAO;
import br.ufes.informatica.marvin.research.domain.Publication;
import br.ufes.informatica.marvin.research.domain.Venue;
import br.ufes.informatica.marvin.research.exceptions.LattesIdNotRegisteredException;
import br.ufes.informatica.marvin.research.exceptions.LattesParseException;
import br.ufes.informatica.marvin.research.persistence.PublicationDAO;
import br.ufes.informatica.marvin.research.persistence.VenueDAO;

/**
 * TODO: document this type.
 *
 * @author Vítor E. Silva Souza (https://github.com/vitorsouza/)
 */
@Stateless
@RolesAllowed({"SysAdmin", "Professor"})
public class UploadLattesCVServiceBean implements UploadLattesCVService {
  /** The unique identifier for a serializable class. */
  private static final long serialVersionUID = 1L;

  /** Logger for this class. */
  private static final Logger logger =
      Logger.getLogger(UploadLattesCVServiceBean.class.getCanonicalName());

  /** TODO: document this field. */
  @EJB
  private AcademicDAO academicDAO;

  /** TODO: document this field. */
  @EJB
  private PublicationDAO publicationDAO;

  /** TODO: document this field. */
  @EJB
  private VenueDAO venueDAO;

  /** TODO: document this field. */
  @Inject
  private Event<MatchPublicationsEvent> matchPublicationsEvent;

  /** TODO: document this field. */
  private PersistentObjectConverterFromId<Venue> venueConverter;

  @Override
  public PersistentObjectConverterFromId<Venue> getVenueConverter() {
    if (venueConverter == null)
      venueConverter = new PersistentObjectConverterFromId<Venue>(venueDAO);
    return venueConverter;
  }

  @Override
  public List<Venue> findVenueByName(String query) {
    return venueDAO.findByNameOrAcronym(query);
  }

  @Override
  public PublicationInfo uploadLattesCV(InputStream inputStream)
      throws LattesIdNotRegisteredException, LattesParseException {
    // Parses the Lattes CV.
    LattesParser parser = new LattesParser(inputStream);
    parser.parse();

    // Retrieves some basic information.
    Long lattesId = parser.getLattesId();
    String researcherName = parser.getResearcherName();

    try {
      // Checks if the curriculum's ID matches an ID registered in the system.
      Academic owner = academicDAO.retrieveByLattesId(lattesId);
      logger.log(Level.INFO, "Found academic with Lattes ID {0}: {1} ({2}).",
          new Object[] {lattesId, owner.getName(), owner.getEmail()});

      // Adds the researcher and the current amount of publications associated with her.
      parser.setResearcher(owner);
      parser.setPreviousQuantity(publicationDAO.retrieveCountByAcademic(owner));
    } catch (PersistentObjectNotFoundException e) {
      // If there is no academic with the given Lattes ID, throw an exception from the domain.
      logger.log(Level.WARNING,
          "No academics found with Lattes ID {0} (name: {1}). Cannot assign production to anyone in the system.",
          new Object[] {lattesId, researcherName});
      throw new LattesIdNotRegisteredException(lattesId, researcherName);
    } catch (MultiplePersistentObjectsFoundException e) {
      // This is a bug. Log and throw a runtime exception.
      logger.log(Level.SEVERE, "Multiple academics found with the same Lattes ID: " + lattesId, e);
      throw new EJBException(e);
    }

    // Returns the set of publications extracted from the CV.
    return parser;
  }

  @Override
  public void assignPublicationsToAcademic(Set<Publication> publications, Academic owner) {
    // Delete the previous publications of the academic.
    List<Publication> previousPublications = publicationDAO.retrieveByAcademic(owner);
    for (Publication previous : previousPublications)
      publicationDAO.delete(previous);

    // Assign the new publications to the academic and save.
    for (Publication publication : publications) {
      publication.setOwner(owner);
      publicationDAO.save(publication);
    }

    // FIXME: the matches need to be confirmed by calling saveMatches(). Therefore, the publications
    // should be detached
    // here. Update JButler, adding detach() method to BaseDAO.

    // Fires an event that triggers the matching between venues and publications.
    matchPublicationsEvent.fire(new MatchPublicationsEvent(owner));
  }

  @Override
  public void saveMatches(Set<Publication> publications) {
    // Saves all publications.
    for (Publication publication : publications) {
      publicationDAO.save(publication);
    }
  }
}

code/marvin/src/main/webapp/research/uploadLattesCV/done.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:adm="http://github.com/adminfaces"
	template="/WEB-INF/templates/template.xhtml">

	<ui:define name="title">
		<h:outputText value="#{msgsResearch['uploadLattesCV.title']}" />
	</ui:define>
    
    <ui:define name="description">
    	<h:outputText value="#{msgsResearch['uploadLattesCV.title.description']}" />
    </ui:define>

  	<ui:define name="body">
		<!-- The breadcrumb. -->
		<adm:breadcrumb title="#{msgsResearch['uploadLattesCV.title']}" link="index.xhtml"/>

		<ui:decorate template="/WEB-INF/templates/form-nobox.xhtml">
			<ui:param name="formName" value="form" />

			<!-- Success message. -->
			<p><h:outputFormat value="#{msgsResearch['uploadLattesCV.text.instructions.success']}">
				<f:param value="#{flash.uploadLattesCVController.publications.size()}" />
				<f:param value="#{flash.uploadLattesCVController.researcher.name}" />
			</h:outputFormat></p>

			<!-- Buttons to take the user to possible next steps. -->	
			<ui:decorate template="/WEB-INF/templates/formbuttonpanel.xhtml">
				<p:commandButton action="#{uploadLattesCVController.cancel}" value="#{msgsResearch['uploadLattesCV.button.uploadAnother']}" icon="fa fa-fw fa-plus" />
			</ui:decorate>
		</ui:decorate>
	</ui:define>
</ui:composition>

code/marvin/src/main/webapp/research/uploadLattesCV/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:adm="http://github.com/adminfaces"
	template="/WEB-INF/templates/template.xhtml">

	<ui:define name="title">
		<h:outputText value="#{msgsResearch['uploadLattesCV.title']}" />
	</ui:define>
    
    <ui:define name="description">
    	<h:outputText value="#{msgsResearch['uploadLattesCV.title.description']}" />
    </ui:define>

  	<ui:define name="body">
		<!-- The breadcrumb. -->
		<adm:breadcrumb title="#{msgsResearch['uploadLattesCV.title']}" link="index.xhtml"/>

		<!-- Instructions on how to get the file to upload. -->
		<p><h:outputText value="#{msgsResearch['uploadLattesCV.text.instructions.upload']}" /></p>

		<!-- The form to be filled in with the file to upload. -->
		<ui:decorate template="/WEB-INF/templates/form.xhtml">
			<ui:param name="formName" value="form" /> 
			<ui:param name="formLabel" value="#{msgsResearch['uploadLattesCV.form.upload']}" />
			<ui:param name="formFileUpload" value="true" /> 
			<p:focus />

			<!-- File chooser field. -->
			<ui:decorate template="/WEB-INF/templates/formfield.xhtml">
				<ui:param name="fieldName" value="file" />
				<ui:param name="label" value="#{msgsResearch['uploadLattesCV.field.file']}" />
				<p:fileUpload id="file" value="#{uploadLattesCVController.file}" mode="simple" skinSimple="true" required="true" label="#{msgs['button.fileUpload']}" />
			</ui:decorate>

			<!-- Upload button. -->
			<ui:decorate template="/WEB-INF/templates/formbuttonpanel.xhtml">
				<p:commandButton ajax="false" action="#{uploadLattesCVController.upload}" value="#{msgsResearch['uploadLattesCV.button.upload']}" icon="fa fa-fw fa-upload" />
			</ui:decorate>
		</ui:decorate>
	</ui:define>
</ui:composition>

	

code/marvin/src/main/webapp/research/uploadLattesCV/list.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:adm="http://github.com/adminfaces"
	template="/WEB-INF/templates/template.xhtml">

	<ui:define name="title">
		<h:outputText value="#{msgsResearch['uploadLattesCV.title']}" />
	</ui:define>
    
    <ui:define name="description">
    	<h:outputText value="#{msgsResearch['uploadLattesCV.title.description']}" />
    </ui:define>

  	<ui:define name="body">
		<!-- The breadcrumb. -->
		<adm:breadcrumb title="#{msgsResearch['uploadLattesCV.title']}" link="index.xhtml"/>

		<!-- Instructions to confirm that the publications should be associated with the academic. -->
		<p><h:outputFormat value="#{msgsResearch['uploadLattesCV.text.instructions.confirm']}">
			<f:param value="#{uploadLattesCVController.researcher.name}" />
			<f:param value="#{uploadLattesCVController.previousQuantity}" />
			<f:param value="#{uploadLattesCVController.publications.size()}" />
		</h:outputFormat></p>
	
		<!-- The listing form. -->
		<ui:decorate template="/WEB-INF/templates/form.xhtml">
			<ui:param name="formName" value="listingForm" />
			<ui:param name="formLabel" value="#{msgsResearch['uploadLattesCV.form.publications']}" />

			<!-- List of publications extracted from the CV file. -->
			<p:dataTable
				widgetVar="listingTable"
				value="#{uploadLattesCVController.publications}" 
				var="entity" 
				selectionMode="single" 
				selection="#{uploadLattesCVController.selectedPublication}" 
				rowKey="#{entity.uuid}"
				emptyMessage="#{msgsResearch['uploadLattesCV.text.noPublications']}"
				reflow="true">

				<p:column headerText="#{msgsResearch['uploadLattesCV.field.type']}" styleClass="ui-grid-col-2">
					<c:set var="typeKey" value="uploadLattesCV.field.type.#{entity.class.simpleName.toLowerCase()}" />
					<h:outputText value="#{msgsResearch[typeKey]}" />
				</p:column>

				<p:column headerText="#{msgsResearch['uploadLattesCV.field.title']}" styleClass="ui-grid-col-9">
					<h:outputText value="#{entity.title}" />
				</p:column>

				<p:column headerText="#{msgsResearch['uploadLattesCV.field.year']}" styleClass="ui-grid-col-1">
					<h:outputText value="#{entity.year}" />
				</p:column>
			</p:dataTable>

			<!-- Buttons shown below the listing. -->
			<ui:decorate template="/WEB-INF/templates/formbuttonpanel.xhtml">
				<p:commandButton action="#{uploadLattesCVController.cancel}" value="#{msgsResearch['uploadLattesCV.button.cancel']}" icon="fa fa-fw fa-ban" />
				<p:commandButton action="#{uploadLattesCVController.confirm}" value="#{msgsResearch['uploadLattesCV.button.confirm']}" icon="fa fa-fw fa-check" />
			</ui:decorate>
		</ui:decorate>
	</ui:define>
</ui:composition>

code/marvin/src/main/webapp/research/uploadLattesCV/match.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:adm="http://github.com/adminfaces"
	template="/WEB-INF/templates/template.xhtml">

	<ui:define name="title">
		<h:outputText value="#{msgsResearch['uploadLattesCV.title']}" />
	</ui:define>
    
    <ui:define name="description">
    	<h:outputText value="#{msgsResearch['uploadLattesCV.title.description']}" />
    </ui:define>

  	<ui:define name="body">
		<!-- The breadcrumb. -->
		<adm:breadcrumb title="#{msgsResearch['uploadLattesCV.title']}" link="index.xhtml"/>

		<!-- Instructions on venue matching. -->
		<p><h:outputFormat value="#{msgsResearch['uploadLattesCV.text.instructions.match']}">
			<f:param value="#{uploadLattesCVController.publications.size()}" />
			<f:param value="#{uploadLattesCVController.researcher.name}" />
		</h:outputFormat></p>
	
		<!-- The listing form. -->
		<ui:decorate template="/WEB-INF/templates/form.xhtml">
			<ui:param name="formName" value="listingForm" />
			<ui:param name="formLabel" value="#{msgsResearch['uploadLattesCV.form.publications']}" />

			<p:dataTable
				widgetVar="listingTable"
				value="#{uploadLattesCVController.papers}" 
				var="entity" 
				selectionMode="single" 
				selection="#{uploadLattesCVController.selectedPublication}" 
				rowKey="#{entity.uuid}"
				emptyMessage="#{msgsResearch['uploadLattesCV.text.noPublications']}"
				reflow="true" editable="true" editMode="cell">

				<p:column headerText="#{msgsResearch['uploadLattesCV.field.year']}" styleClass="ui-grid-col-1">
					<h:outputText value="#{entity.year}" />
				</p:column>

				<p:column headerText="#{msgsResearch['uploadLattesCV.field.title']}" styleClass="ui-grid-col-4">
					<h:outputText value="#{entity.title}" />
				</p:column>

				<p:column headerText="#{msgsResearch['uploadLattesCV.field.venueString']}" styleClass="ui-grid-col-4">
					<h:outputText value="#{entity.venueString}" />
				</p:column>

				<p:column headerText="#{msgsResearch['uploadLattesCV.field.venue']}" styleClass="ui-grid-col-3">
					<p:cellEditor>
						<f:facet name="output">
							<h:outputText value="#{msgsResearch['uploadLattesCV.text.noVenue']}" rendered="#{entity.venue == null}" />
							<h:outputText value="#{entity.venue.name}" rendered="#{entity.venue != null}" />
						</f:facet>
						<f:facet name="input">
							<p:autoComplete id="venue" value="#{entity.venue}" completeMethod="#{uploadLattesCVController.completeVenues}" var="venue" itemLabel="#{venue.name}" itemValue="#{venue}" converter="#{uploadLattesCVController.venueConverter}" forceSelection="true" />
						</f:facet>
					</p:cellEditor>
				</p:column>
			</p:dataTable>

			<!-- Buttons shown below the listing. -->
			<ui:decorate template="/WEB-INF/templates/formbuttonpanel.xhtml">
				<p:commandButton action="#{uploadLattesCVController.cancel}" value="#{msgsResearch['uploadLattesCV.button.cancel']}" icon="fa fa-fw fa-ban" />
				<p:commandButton action="#{uploadLattesCVController.match}" value="#{msgsResearch['uploadLattesCV.button.confirm']}" icon="fa fa-fw fa-check" />
			</ui:decorate>
		</ui:decorate>
	</ui:define>
</ui:composition>